---
name: Non-destructive Merge

on:
  pull_request:
    types:
      - closed
#  branches:
#    - 'main-*'

jobs:
  ff_merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Print all branches (pre-fetch)
      run: "git branch --format '%(objectname:short) %(refname) upstream: %(upstream)' --all"
    - name: Output value of GITHUB_EVENT_PATH
      run: echo $GITHUB_EVENT_PATH
    - name: Output value of GITHUB_EVENT_PATH
      run: echo $GITHUB_EVENT_PATH
    - name: Output content of GITHUB_EVENT_PATH
      run: cat $GITHUB_EVENT_PATH
    - name: Formatted output content of GITHUB_EVENT_PATH
      run: cat $GITHUB_EVENT_PATH | jq '.'
    - name: Fetch PR branch
      run: git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
    - name: Status, Post-fetch PR branch
      run: git status
    - name: Set git user.email and user.name
      run: git config --global user.email "msgh-action"; git config --global user.name "robot"
    - name: Merge PR branch
      run: git merge --ff-only pr-branch
    - name: Print all branches (pre-push)
      run: "git branch --format '%(objectname:short) %(refname) upstream: %(upstream)' --all"
    - name: Push changes
      env:
        TOKEN: ${{ secrets.MSGH_TOKEN }}
      run: git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git main:main
